services:

  api:
    container_name: api_gateway
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      service_auth:
        condition: service_started
    restart: on-failure

  service_auth:
    container_name: service_auth
    build:
      context: ./service_authentification
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_USER_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_BD_USER}
      - PYTHONUNBUFFERED=1
    depends_on:
      user_db:
        condition: service_started
    restart: on-failure
  
  service_log:
    container_name: service_log
    build:
      context: ./service_log
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      DB_HOST: log_db
      DB_NAME: log_db
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      log_db:
        condition: service_started
    restart: on-failure
          
  user_db:
    image: postgres
    container_name: user_db
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: user_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user

  log_db:
    image: postgres
    container_name: log_db
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: log_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


#- DATABASE_LOG_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_LOG}
#- DATABASE_PM1_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_PM1}