services:

  api:
    container_name: api_gateway
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      service_auth:
        condition: service_started
    restart: on-failure

  service_auth:
    container_name: service_auth
    build:
      context: ./service_authentification
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_USER_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_BD_USER}
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_started
    restart: on-failure
        
  db:
    image: postgres:15
    container_name: prostgres_dbs
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./databases/provisioning:/docker-entrypoint-initdb.d

    ports:
      - "5433:5432"

    restart: on-failure


volumes:
  pgdata:


#- DATABASE_LOG_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_LOG}
#- DATABASE_PM1_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_PM1}